apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: data-analyst-agent
type: Opaque
stringData:
  OPENAI_API_KEY: "TU_API_KEY"
  LITELLM_MASTER_KEY: "sk-local-secret"
  AGENT_DATABASE_URL: "postgresql://agent:agent@app-postgres-agent:5432/agent"
  ANALYTICS_DATABASE_URL: "postgresql://analyst_agent:analyst@app-postgres-analytics:5432/analytics"
  REDIS_URL: "redis://app-redis:6379/0"
  ANALYST_MODEL: "analyst-local-fast"
  LITELLM_DATABASE_URL: "postgresql://litellm:litellm@litellm-db:5432/litellm"
  LITELLM_REDIS_URL: "redis://litellm-redis:6379/0"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-postgres-agent-credentials
  namespace: data-analyst-agent
type: Opaque
stringData:
  POSTGRES_DB: "agent"
  POSTGRES_USER: "agent"
  POSTGRES_PASSWORD: "agent"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-postgres-analytics-credentials
  namespace: data-analyst-agent
type: Opaque
stringData:
  POSTGRES_DB: "analytics"
  POSTGRES_USER: "analytics_admin"
  POSTGRES_PASSWORD: "analytics_admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: litellm-db-credentials
  namespace: data-analyst-agent
type: Opaque
stringData:
  POSTGRES_DB: "litellm"
  POSTGRES_USER: "litellm"
  POSTGRES_PASSWORD: "litellm"