apiVersion: v1
kind: Service
metadata:
  name: api-elb
  namespace: ${namespace}
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate: |
      {
        "type": "public",
        "name": "analyst-api-elb",
        "bandwidth_name": "analyst-api-bw",
        "bandwidth_chargemode": "bandwidth",
        "bandwidth_size": 5,
        "bandwidth_sharetype": "PER",
        "eip_type": "5_bgp"
      }
    kubernetes.io/elb.health-check-flag: "on"
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: 8000
