apiVersion: v1
kind: Service
metadata:
  name: litellm-elb
  namespace: data-analyst-agent
  annotations:
    kubernetes.io/elb.class: union
    kubernetes.io/elb.autocreate: |
      {
        "type": "public",
        "name": "analyst-litellm-elb",
        "bandwidth_name": "analyst-litellm-bw",
        "bandwidth_chargemode": "bandwidth",
        "bandwidth_size": 5,
        "bandwidth_sharetype": "PER",
        "eip_type": "5_bgp"
      }
    kubernetes.io/elb.health-check-flag: "on"
    kubernetes.io/elb.health-check-option: |
      {
        "protocol": "HTTP",
        "port": 4000,
        "path": "/health/liveness",
        "delay": "5",
        "timeout": "3",
        "max_retries": "3"
      }
spec:
  type: LoadBalancer
  selector:
    app: litellm
  ports:
    - port: 4000
      targetPort: 4000
